### ISSUE TITLE
typo "initialized"

### ISSUE THREAD

**Issue by heroxbd** [scim-im/scim#10]
This is from the output of lintian:

extras/immodules/client-common/scim-bridge-client.c
1233:        scim_bridge_perrorln ("The client library is not intialized at scim_bridge_client_read_and_dispatch ()");

"intialized" should be "initialized"

**Comment by leggewie** [comment]
Thanks, heroxbd.

I think it's easier if you clone the git repo, make your changes and then shoot us a pull request instead of opening a number of bug tickets with small, but valid issues.

**Comment by heroxbd** [comment]
Hi Rolf.  I think a small issue like a typo is not worth a PR.  Just a reminder in the issue tracker is enough.

**Comment by leggewie** [comment]
A PR is much easier handle than a ticket.

PR:
1) inspect changes
2) hit "Accept" button

Done

Ticket:
1) inspect changes
2) code changes
3) commit changes, tag to close ticket
4) push changes

And tickets have to be dealt with individually while even 100 changesets with similarly small, but valid patches can be merged in a single step.  For a single ticket the difference is negligible.  I was assuming you'd open a few more of these.

**Comment by tzhuan** [comment]
Fixed, thank you.
