### ISSUE TITLE
Problem with GNOME 3.20

### ISSUE THREAD

**Issue by drunkard** [scim-im/scim#11]
scim-pinyin got trouble with GNOME 3.20, so some work needed before GNOME 3.20. I think it's scim problem, is it right?

Here's my trouble suffering:

1. scim-pinyin can not work with gtk 3.20 programs, even gnome-terminal, but it works with gtk 2 programs, but,
2. while scim-pinyin working with gtk 2 programs, the input buffer area is blank, but it should be chars typed and related I18N words. See the bug image I attached.

Here's photo: https://bugs.gentoo.org/attachment.cgi?id=434336&action=edit

**Comment by tzhuan** [comment]
Thank you for the report. For 1., I'll try to find a box with gnome 3.20 to investigate it. For 2., which version of scim do you use? Could you please try the latest master to see if it still has the problem or not? Thank you very much.

**Comment by drunkard** [comment]
Great work, latest master fixed problem 2.

**Comment by drunkard** [comment]
I was using 1.4.16, sorry for missing.

**Comment by tzhuan** [comment]
Fixed in release 1.4.17.
