### ISSUE TITLE
Can not input non-Chinese characters in GNOME 3.20

### ISSUE THREAD

**Issue by drunkard** [scim-im/scim#12]
I'm using latest master of SCIM (scim-pinyin) and GNOME 3.20, Chinese input is fine, but with SCIM switched on, and pressed SHIFT,

 1) I can not input English chars, halfwidth chars, half width punctuation mark. numbers.
 2) In Chinese input mode, I can't input upper case letters, it worked before GNOME 3.20.

I think they are the same issue, non-unicode chars ignored by SCIM, is that true?

**Comment by tzhuan** [comment]
Well, I am not sure currently. However, there are two sets of gtk-im-module: one is from scim and the other one is from scim-bridge, which is the default one currently.

Could you please configure the latest master with `--enable-orig-gtk2-immodule --enable-orig-gtk3-immodule` then set the `GTK_IM_MODULE` environment variable to `scim-orig` to see if things change? I want to know that both gtk-im-modules have the problem or only the gtk-im-module from scim-bridge has the problem.

Note that you might need to run `/usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0` and `/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0` manually to update the gtk2/gtk3 im-module caches.

**Comment by drunkard** [comment]
Yes, there's no problem with `scim-orig`.

**Comment by tzhuan** [comment]
Thank you very much for the test. The results suggest me that the root of the issue is the same as #2. I have planed the schedules to handle it already.

**Comment by tzhuan** [comment]
Hi, I have pushed a fix to master. Could you please try the master to see if the issue is resolved? Thanks.

**Comment by drunkard** [comment]
Great work, it works now. Thank you very much :-)

**Comment by tzhuan** [comment]
Great! I'll make a new release soon.

**Comment by tzhuan** [comment]
Fixed in release 1.4.17.
