### ISSUE TITLE
te-inscript table

### ISSUE THREAD

**Issue by heavytull** [scim-im/scim#18]
The official inscript table for telugu is binding the key " _ " to the telugu sign "VISARGA" which code is 0C03, and sign is " ః ". This table in scim is binding " _ " to itself, i.e. " _ ", and there is no alternative binding to "VISARGA" sign. So it is not possible to input this sign with scim.

**Comment by leggewie** [comment]
Thank you for making us aware of this issue.  None of the developers speaks Telugu, I'm certain.  Are you code-savvy to provide a patch?

**Comment by leggewie** [comment]
This is actually a bug in scim-table, if anything.  Please report it at https://github.com/scim-im/scim-tables/issues

Please be sure to include information about version of scim and scim-tables you are using.  Thank you.
