### ISSUE TITLE
Backspace and delete keys dysfunctional in some GTK+ applications

### ISSUE THREAD

**Issue by arteme** [scim-im/scim#2]
The issue, as seen in some GTK+ applications is that when SCIM IM is turned on, 
 * pressing the backspace key enters text equivalent to typing: `<Ctrl+Shift+U> 0008 <Enter>`
 * pressing the delete key enters n text equivalent to typing: `<Ctrl+Shift+U> 007F <Enter>`

This issue has shown up for version 1.4.14 users or various platforms:
 * https://bugs.launchpad.net/ubuntu/+source/gedit/+bug/1315579
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747154
 * seen in Arch by myself

**Comment by leggewie** [comment]
@tzhuan Can you have a look?

**Comment by tzhuan** [comment]
Okay, I'll handle it.

**Comment by muellert** [comment]
Hi,

On Mon, Mar 16, 2015 at 07:35:30PM -0700, Tz-Huan Huang wrote:
> Okay, I'll handle it.

I should note that I have no access to my development machine for some
time to go, and that it would thus be wise to not rely on my doing
anything meaningful, and in short time.


Kind regards,
--Toni++

**Comment by leggewie** [comment]
tzhuan, any news?

**Comment by tzhuan** [comment]
I am overhauling and re-writing some parts:
  1. implement a pure C core lib (replace some functions provided by scim-bridge)
  1. remove codes with duplicate functions (some of them are from scim-bridge)
  1. upgrade c++98 to c++11/14
  1. support qt5 and wayland

After 1. and 2. are finished this issue will be resolved. Currently I am doing 1. now.

**Comment by leggewie** [comment]
@tzhuan, thank you for the update and your work.

**Comment by tzhuan** [comment]
I am trying to implement 1. and 2. mentioned above but I find that there are far more tasks than I thought. Therefore, I decide to fix this issue first. I believe the latest commit (fcc14b77630e9adb30015f017837fc3b62d3ca57) resolved this issue.

**Comment by tzhuan** [comment]
Fixed in release 1.4.17.
