### ISSUE TITLE
Spelling errors in scim's source files

### ISSUE THREAD

**Issue by hughmcmaster** [scim-im/scim#25]
Hi,

Debian's package checker, lintian, picked up some spelling errors in the source code. These are fixed in the attached patch. Apply it by renaming the file to end in .patch instead of .txt.

Thank you,

Hugh

[03_scim_spelling_fixes.patch.txt](https://github.com/scim-im/scim/files/2115277/03_scim_spelling_fixes.patch.txt)

**Comment by leggewie** [comment]
Sorry for the slow response. Looks good to me.  Do you know how to open a PR here on github?
