### ISSUE TITLE
[RPMLINT]  Cannot load module /usr/lib64/gtk-3.0/3.0.0/immodules/im-scim.so:

### ISSUE THREAD

**Issue by posophe** [scim-im/scim#4]
I have this issue with scim 1.4.15
Cannot load module /usr/lib64/gtk-3.0/3.0.0/immodules/im-scim.so: /usr/lib64/gtk-3.0/3.0.0/immodules/im-scim.so: undefined symbol: gdk_x11_drawable_get_xdisplay
/usr/lib64/gtk-3.0/3.0.0/immodules/im-scim.so does not export GTK+ IM module API: /usr/lib64/gtk-3.0/3.0.0/immodules/im-scim.so: undefined symbol: gdk_x11_drawable_get_xdisplay

**Comment by tzhuan** [comment]
Please apply this patch 88fbabed7dc236642021f8263f1b25bf67c6806e and rebuild it.

**Comment by posophe** [comment]
It's working. Thanks :)
