### ISSUE TITLE
想要写一个基于scim的输入法插件

### ISSUE THREAD

**Issue by hantengc** [scim-im/scim#40]
有个问题想要咨询一下：
1. 基于scim的输入法是否需要一个配置文件安装到scim的某个目录下?其他输入法框架都有一个其规定的输入法配置文件写法，需要安装到对应的目录下，这样输入法才会被输入法框架加载。
2. scim只能通过命令行重新启动scim来查看debug日志是吗？

期待回复！~

**Comment by hantengc** [comment]
@suzhe

**Comment by tzhuan** [comment]
> 有个问题想要咨询一下：
> 
>     1. 基于scim的输入法是否需要一个配置文件安装到scim的某个目录下?其他输入法框架都有一个其规定的输入法配置文件写法，需要安装到对应的目录下，这样输入法才会被输入法框架加载。

No configuration file is needed at all.
The scim main program will traverse `*.so` files under the `{prefix}/lib/scim-{major-version}/{minor-version}/` for every module (`FrontEnd`, `IMEngine`, `Config`, etc) and load them automatically. 
 
>     2. scim只能通过命令行重新启动scim来查看debug日志是吗？

As far as I know, yes.

> 期待回复！~

**Comment by hantengc** [comment]
> > 有个问题想要咨询一下：
> > ```
> > 1. 基于scim的输入法是否需要一个配置文件安装到scim的某个目录下?其他输入法框架都有一个其规定的输入法配置文件写法，需要安装到对应的目录下，这样输入法才会被输入法框架加载。
> > ```
> 
> No configuration file is needed at all. The scim main program will traverse `*.so` files under the `{prefix}/lib/scim-{major-version}/{minor-version}/` for every module (`FrontEnd`, `IMEngine`, `Config`, etc) and load them automatically.
> 
> > ```
> > 2. scim只能通过命令行重新启动scim来查看debug日志是吗？
> > ```
> 
> As far as I know, yes.
> 
> > 期待回复！~

大神，我自己写了一个demo，通过scim-setup我发现一直没有显示出来我自己的输入法。不知道是哪里出问题了，方便帮忙看看指正一下吗？

仓库地址：https://gitee.com/hantengc/scim-simpleinputmethod

**Comment by hantengc** [comment]
或者说怎么可以联系到您呢？我看你之前的清华邮箱已经没办法接收邮件了。我自己的vx：brave_033333  邮箱是：hantengwy@163.com

不知道是否方便单独加一下您~ 期待您的回复！！！

**Comment by hantengc** [comment]
@suzhe

**Comment by tzhuan** [comment]
> > > 有个问题想要咨询一下：
> > > ```
> > > 1. 基于scim的输入法是否需要一个配置文件安装到scim的某个目录下?其他输入法框架都有一个其规定的输入法配置文件写法，需要安装到对应的目录下，这样输入法才会被输入法框架加载。
> > > ```
> > 
> > 
> > No configuration file is needed at all. The scim main program will traverse `*.so` files under the `{prefix}/lib/scim-{major-version}/{minor-version}/` for every module (`FrontEnd`, `IMEngine`, `Config`, etc) and load them automatically.
> > > ```
> > > 2. scim只能通过命令行重新启动scim来查看debug日志是吗？
> > > ```
> > 
> > 
> > As far as I know, yes.
> > > 期待回复！~
> 
> 大神，我自己写了一个demo，通过scim-setup我发现一直没有显示出来我自己的输入法。不知道是哪里出问题了，方便帮忙看看指正一下吗？
> 
> 仓库地址：https://gitee.com/hantengc/scim-simpleinputmethod

You may build the scim with debug enabled and specify the debug flag to see if your module is loaded correctly.

By the way, I believe that suzhe has not been active in this project for a while.

**Comment by hantengc** [comment]
> > > > 有个问题想要咨询一下：
> > > > ```
> > > > 1. 基于scim的输入法是否需要一个配置文件安装到scim的某个目录下?其他输入法框架都有一个其规定的输入法配置文件写法，需要安装到对应的目录下，这样输入法才会被输入法框架加载。
> > > > ```
> > > 
> > > 
> > > No configuration file is needed at all. The scim main program will traverse `*.so` files under the `{prefix}/lib/scim-{major-version}/{minor-version}/` for every module (`FrontEnd`, `IMEngine`, `Config`, etc) and load them automatically.
> > > > ```
> > > > 2. scim只能通过命令行重新启动scim来查看debug日志是吗？
> > > > ```
> > > 
> > > 
> > > As far as I know, yes.
> > > > 期待回复！~
> > 
> > 
> > 大神，我自己写了一个demo，通过scim-setup我发现一直没有显示出来我自己的输入法。不知道是哪里出问题了，方便帮忙看看指正一下吗？
> > 仓库地址：https://gitee.com/hantengc/scim-simpleinputmethod
> 
> You may build the scim with debug enabled and specify the debug flag to see if your module is loaded correctly.
> 
> By the way, I believe that suzhe has not been active in this project for a while.

我确定我的插件时被加载了的，因为在我的代码里面module init 和create factory都有打印输出，但是create_instance函数一直没有被调用到，不知道这里没有被scim调用到是什么原因。。。

**Comment by hantengc** [comment]
@tzhuan 请问现在是您主要负责scim吗? 方便单独加一下联系方式来讨论下问题吗！
