### ISSUE TITLE
Can't compile out of srcdir

### ISSUE THREAD

**Issue by davispuh** [scim-im/scim#8]
When trying to compile out of source dir like `mkdir build && cd build && ./../configure && make` it errors with
```
In file included from ../../.././../extras/immodules/agent/scim-bridge-agent.cpp:44:0:
../../.././../src/scim.h:278:28: fatal error: scim_types.h: No such file or directory
```

**Comment by tzhuan** [comment]
Thank for the report. While I am not familiar with the autoconf building system, I don't think I can address this issue soon...

**Comment by davispuh** [comment]
Me neither, I prefer [CMake](http://www.cmake.org/).

It's something to do with includes as you can see in `scim.h` there's
`#include <scim_types.h>` which would indicate that path should be added to `-I`, so some flag configuration.

Anyway it's not a big deal so nothing to rush.

**Comment by leggewie** [comment]
FWIW, I was able to verify the problem with HEAD today.

**Comment by tzhuan** [comment]
Solved, thank you!
